
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz-runs = 100
solc_version = "0.7.6"    # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer = true          # Enable or disable the solc optimizer
optimizer_runs = 200      # The number of optimizer runs
verbosity = 3             # The verbosity of tests
remappings = [
    'tinlake-auth/=lib/tinlake-auth/src/',
    'tinlake-erc20/=lib/tinlake-erc20/src/',
    'tinlake-math/=lib/tinlake-math/src/',
    'tinlake-title/=lib/tinlake-title/src/',
]

# Required for the deployment script
fs_permissions = [{ access = "read", path = "./out"}]

[profile.pull_request]
fuzz_runs = 1000

[profile.push_to_main]
fuzz_runs = 50000
fuzz_max_global_rejects = 262144
fuzz_max_local_rejects = 4096