name: Tests
on:
  pull_request:
  push:
    branches: [ develop ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: centrifuge-tinlake
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: install
      run: nix-shell --run "make install"
    - name: lint
      run: nix-shell --run "make lint"
    - name: test
      if: ${{ github.event_name == 'pull_request' }}
      run: nix-shell --run "make test"
    - name: test deep
      if: ${{ github.event_name == 'push' }}
      run: nix-shell --run "make test_deep"
